### ISSUE TITLE
fn should be optional

### ISSUE THREAD

**Issue by aluetjen** [anotheri/express-routescan#1]
Maybe "fn" in the route hashtable should be optional. It is valid just to define a middleware.

My use case is to register passport.js routes:

module.exports = {
    '/auth/twitter': {
        method: 'GET',
        middleware: [passport.authenticate('twitter')]
    },
    '/auth/twitter/callback': {
        method: 'GET',
        middleware: [passport.authenticate('twitter', {
            successRedirect: '/',
            failureRedirect: '/login'
        })]
    }
};

**Comment by anotheri** [comment]
Hmm, it basics to Express JS routing. I've never seen such use case in [Express JS routing documentation](http://expressjs.com/api.html#app.VERB):

``` javascript
'/auth/twitter': {
    method: 'GET',
    middleware: [passport.authenticate('twitter')]
}
```

It will be converted to `app.get('/auth/twitter', [passport.authenticate('twitter')], undefined)`, but it's wrong.

If you try to use Passport for the authentication with twitter account:

``` javascript
// Redirect the user to Twitter for authentication. When complete, Twitter
// will redirect the user back to the application at
//   /auth/twitter/callback
app.get('/auth/twitter', passport.authenticate('twitter'));

// Twitter will redirect the user to this URL after approval.  Finish the
// authentication process by attempting to obtain an access token.  If
// access was granted, the user will be logged in.  Otherwise,
// authentication has failed.
app.get('/auth/twitter/callback', 
  passport.authenticate('twitter', { successRedirect: '/',
                                     failureRedirect: '/login' }));
```

you should use `fn` key instead of `middleware`:

``` javascript
module.exports = {
    '/auth/twitter': {
        method: 'GET',
        fn: passport.authenticate('twitter')
    },
    '/auth/twitter/callback': {
        method: 'GET',
        fn: passport.authenticate('twitter', {
            successRedirect: '/',
            failureRedirect: '/login'
        })
    }
};
```

**Comment by anotheri** [comment]
By the way, you can use shortcut route definition in your case (only for `GET` method):

``` javascript
module.exports = {
    '/auth/twitter': passport.authenticate('twitter'),
    '/auth/twitter/callback': passport.authenticate('twitter', {
        successRedirect: '/',
        failureRedirect: '/login'
    })
};
```

**Comment by aluetjen** [comment]
Agreed. I read the passport.js docs again and what I suggested there is nonsense :)

**Comment by anotheri** [comment]
no problem. good luck. =)
