### ISSUE TITLE
No next parameter found

### ISSUE THREAD

**Issue by ghost** [anotheri/express-routescan#4]
I haven't reviewed all of your code, can you please tell me if pass the next parameter to all routes. I need it for handling errors.

**Comment by anotheri** [comment]
Thanks for this use case. I've disabled `all` method here:
https://github.com/anotheri/express-routescan/blob/master/lib/getValidMethods.js#L18-19

I'm going to add specific option into configuration to handle this parameter.
But for now you can just set it `true` locally. And use next route config for handling errors:

``` javascript
module.exports = {
    /* for all routes */
    '*': {
        /* and for all methods */
        methods: [ 'all' ],
        fn: function ( req, res, next ) {
            /* use this error handler as middleware */
            next();
        }
    }
};
```

I hope it helped.

**Comment by ghost** [comment]
cool thanks

**Comment by anotheri** [comment]
Hey @ezraspectre 
I've just added `strictMode` option that you can see in readme. And default value for it is `false`, so you don't need to set anything extra configuration options to implement your use case.

**Comment by ghost** [comment]
much appreciated

**Comment by anotheri** [comment]
@ezraspectre 
I've just added the support for `use` method. It might work better for you than `all` method.
Check [readme](https://github.com/anotheri/express-routescan#middleware-with-use-method-loggers-error-handlers-etc) to get more info.
