### ISSUE TITLE
Catching 404s and the like

### ISSUE THREAD

**Issue by MaffooBristol** [anotheri/express-routescan#6]
Hi,

I've just started playing with this module, but I've been unable to recreate my previous fall-through route, where I would define `app.use()` with no route parameter and catch all invalid routes.

I can't seem to find a way of doing this using express-routescan, as if I use a blank route param it throws up an error.

Any ideas? Or am I missing something!

Many thanks
Matt

Ps, at the moment my only option is to define a `/404` route using routescan, and then at the end of my app.js file, putting a redirect, but I want to keep the broken path rather than redirecting:

``` javascript
app.use(function (req, res) {
  res.redirect('/404');
});
```

**Comment by anotheri** [comment]
I'm not sure, but it seems you need a middleware like this:

```
module.exports = {
    /* for all routes */
    '*': {
        /* and for all methods */
        methods: [ 'all' ],
        fn: function ( req, res, next ) {
            /* use this error handler as middleware. */
            next();
        }
    }
};
```

Let me know if it helped or not.

**Comment by MaffooBristol** [comment]
Cheers for the feedback- that code seems to run before anything else, though. So it just overwrites every single request and 404s everything!

**Comment by anotheri** [comment]
Yes, you're right... well, I've got what you need.
I'll try to implement some solution for this.

**Comment by MaffooBristol** [comment]
Lovely, thanks :)

**Comment by anotheri** [comment]
@MaffooBristol 
I've jsut added functionality for your usecase.
Check [this paragraph](https://github.com/anotheri/express-routescan#middleware-with-use-method-loggers-error-handlers-etc) and try the last example in it (the one with `deferred: true`).
